version: "3"

services:
  app:
    build: . # Localização do Dockerfile
    command: yarn dev # Comando que quero executar quando a aplicação subir
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app